services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: gptset_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/srv/app
      - ./alembic:/srv/alembic
      - ./alembic.ini:/srv/alembic.ini
    environment:
      DATABASE_URL_SYNC: postgresql://postgres:password@db:5432/gptset_dev
      DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/gptset_dev
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    entrypoint: ["npm", "run", "dev"]
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node_modules_frontend:/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE_URL=http://backend:8000
    depends_on:
      - backend

volumes:
  postgres_data:
  node_modules_frontend:
