line-length = 120
src = ["app", "tests"]
target-version = "py311"

[lint]
select = ["E", "F", "I"]
extend-select = ["TID", "TID252"]
fixable = ["ALL"]

[lint.isort]
known-first-party = ["app"]

[lint.per-file-ignores]
"alembic/*" = ["E402"]

[format]
