"""create trades table

Revision ID: 690ffec9e9e7
Revises: 2f8dbe8b6d6c
Create Date: 2025-07-15 16:08:29.870852

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "690ffec9e9e7"
down_revision: Union[str, Sequence[str], None] = "2f8dbe8b6d6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trades", sa.Column("stock_code", sa.String(), nullable=False))
    op.add_column("trades", sa.Column("quantity", sa.Integer(), nullable=False))
    op.add_column("trades", sa.Column("entry_price", sa.Float(), nullable=False))
    op.add_column("trades", sa.Column("description", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trades", "description")
    op.drop_column("trades", "entry_price")
    op.drop_column("trades", "quantity")
    op.drop_column("trades", "stock_code")
    # ### end Alembic commands ###
