name: Backend CI

on:
  push:
    paths:
      - "app/**"
      - "tests/**"
      - "alembic/**"
      - "scripts/check_import_paths.py"
      - "pyproject.toml"
      - "test_*.py"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    paths:
      - "app/**"
      - "tests/**"
      - "alembic/**"
      - "scripts/check_import_paths.py"
      - "pyproject.toml"
      - "test_*.py"
      - ".github/workflows/backend-ci.yml"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; else pip install pytest ruff; fi

      - name: Show tool versions
        run: |
          python --version
          pip show ruff || true
          ruff --version || true

      - name: Ruff (autofix)
        run: |
          ruff check . --fix
          ruff format .

      - name: Fail if changes left
        run: |
          git update-index -q --refresh
          git diff --exit-code || (echo "::error::Run 'ruff check --fix' locally and commit."; exit 1)

      - name: Validate import prefixes
        run: python scripts/check_import_paths.py

      - name: Run pytest (critical path)
        run: python -m pytest tests/test_chat_message_delete.py
