name: branch-protection/sync

on:
  workflow_dispatch:

permissions:
  contents: read
  administration: write

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Apply branch protection for main
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const branch = 'main';
            const requiredChecks = ['plan-sync/Validate'];

            await github.rest.repos.updateBranchProtection({
              owner,
              repo,
              branch,
              required_status_checks: {
                strict: true,
                contexts: requiredChecks,
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                required_approving_review_count: 0,
                dismiss_stale_reviews: false,
                require_code_owner_reviews: false,
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false,
              block_creations: false,
              lock_branch: false,
              required_linear_history: true,
              allow_fork_syncing: false,
              required_conversation_resolution: true,
            });

            core.info(`Updated branch protection for ${owner}/${repo}@${branch}`);
            core.info(`Required checks enforced: ${requiredChecks.join(', ')}`);
