name: docsync-report-append

on:
  workflow_run:
    workflows:
      - docsync-check
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  append:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      pull-requests: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    concurrency:
      group: report-${{ github.event.workflow_run.id }}
      cancel-in-progress: true
    steps:
      - name: Checkout default branch (not the triggering ref)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0

      - name: Download docsync artifacts
        uses: actions/download-artifact@v4
        with:
          name: docsync-artifacts
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: docsync-artifacts

      - name: Append line to docs/agile/report.md
        run: |
          python - <<'PY'
          import json, datetime, zoneinfo, pathlib
          repo = "${{ github.repository }}"
          run_id = "${{ github.event.workflow_run.id }}"
          plan_path = pathlib.Path("docsync-artifacts/doc_sync_plan.json")
          d = json.loads(plan_path.read_text(encoding="utf-8"))

          jst = zoneinfo.ZoneInfo("Asia/Tokyo")
          date = datetime.datetime.now(jst).date().isoformat()
          event = "docsync-check"
          branch = d.get("target","-").split("/")[-1]
          equal  = str(d.get("equal")).lower()
          s = d.get("stats",{})
          src = s.get("src_paths","-")
          tgt = s.get("tgt_paths","-")
          run = f"https://github.com/{repo}/actions/runs/{run_id}"
          line = f"| {date} | {event} | {branch} | {equal} | {src} | {tgt} | {run} |"

          rp  = pathlib.Path("docs/agile/report.md")
          txt = rp.read_text(encoding="utf-8")
          if line not in txt:
              rp.write_text(txt.rstrip() + "\n" + line + "\n", encoding="utf-8")
          PY

      - name: Create GitHub App token
        id: app-token
        if: ${{ secrets.GH_APP_ID != '' && secrets.GH_INSTALLATION_ID != '' && secrets.GH_APP_PRIVATE_KEY != '' }}
        continue-on-error: true
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          installation-id: ${{ secrets.GH_INSTALLATION_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Create PR for report line
        uses: peter-evans/create-pull-request@v6
        continue-on-error: true
        with:
          token: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
          branch: docs-sync/report-${{ github.run_id }}
          title: "[skip docsync] docs: append DocSync report line"
          commit-message: "docs(auto): append report line from docsync-check run"
          labels: "docsync:needs-apply"
