name: docsync-aggregate
on:
  workflow_run:
    workflows: ["docsync-check"]
    types: [completed]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: docsync-aggregate
  cancel-in-progress: true

jobs:
  append:
    if: ${{ github.event.workflow_run.conclusion != 'cancelled' }}
    runs-on: ubuntu-latest
    env:
      TRIGGER_RUN_ID: ${{ github.event.workflow_run.id }}
      TRIGGER_BRANCH: ${{ github.event.workflow_run.head_branch }}
      REPO: ${{ github.repository }}
      SERVER_URL: ${{ github.server_url }}
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Download docsync artifacts from triggering run
        uses: actions/download-artifact@v4
        with:
          name: docsync-artifacts
          path: artifacts
          run-id: ${{ env.TRIGGER_RUN_ID }}

      - name: Build table row
        id: row
        run: |
          python - <<'PY' > row.txt
import json, pathlib, datetime, os
p = pathlib.Path('artifacts/doc_sync_plan.json')
d = json.loads(p.read_text()) if p.exists() else {}
stats = d.get('stats', {})
equal = str(d.get('equal','unknown')).lower()
src   = stats.get('src_paths','-')
tgt   = stats.get('tgt_paths','-')
jst   = datetime.timezone(datetime.timedelta(hours=9))
date  = datetime.datetime.now(jst).strftime('%Y-%m-%d')
run_url = f"{os.environ['SERVER_URL']}/{os.environ['REPO']}/actions/runs/{os.environ['TRIGGER_RUN_ID']}"
branch  = os.environ.get('TRIGGER_BRANCH','-')
print(f"| {date} | docsync-check | {branch} | {equal} | {src} | {tgt} | {run_url} |")
PY

      - name: Append to report.md
        run: |
          echo "$(cat row.txt)" >> docs/agile/report.md

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: docs-sync/report-${{ env.TRIGGER_RUN_ID }}
          commit-message: "docs(report): append row to report.md [skip docsync]"
          title: "docs(report): append row to report.md [skip docsync]"
          body: "Automated append from docsync-aggregate."
          add-paths: |
            docs/agile/report.md
          labels: |
            docsync:needs-apply
