name: docs-index-validate

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/docs-index-validate.yml'

permissions:
  contents: read

concurrency:
  group: docs-index-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: No-op on docs-sync or skip-title PR
        if: ${{ (github.event_name == 'pull_request' && startsWith(github.head_ref, 'docs-sync/')) || (github.event_name != 'pull_request' && startsWith(github.ref_name, 'docs-sync/')) || (github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[skip docsync]')) }}
        run: 'echo "docs-sync/skip-title PR: no-op (success)"'
      - uses: actions/checkout@v4
        if: ${{ !(github.event_name == 'pull_request' && startsWith(github.head_ref, 'docs-sync/')) && !(github.event_name != 'pull_request' && startsWith(github.ref_name, 'docs-sync/')) && !(github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[skip docsync]')) }}
      - uses: actions/setup-python@v5
        if: ${{ !(github.event_name == 'pull_request' && startsWith(github.head_ref, 'docs-sync/')) && !(github.event_name != 'pull_request' && startsWith(github.ref_name, 'docs-sync/')) && !(github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[skip docsync]')) }}
        with:
          python-version: '3.11'
      - name: Validate docs index & links
        if: ${{ !(github.event_name == 'pull_request' && startsWith(github.head_ref, 'docs-sync/')) && !(github.event_name != 'pull_request' && startsWith(github.ref_name, 'docs-sync/')) && !(github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[skip docsync]')) }}
        run: |
          python scripts/docs_index_validate.py || EXIT=$?
          echo "exit_code=${EXIT:-0}" >> $GITHUB_OUTPUT
          exit ${EXIT:-0}
      - name: Write summary
        if: ${{ always() && !(github.event_name == 'pull_request' && startsWith(github.head_ref, 'docs-sync/')) && !(github.event_name != 'pull_request' && startsWith(github.ref_name, 'docs-sync/')) && !(github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[skip docsync]')) }}
        run: |
          echo "## DS-14 Report" >> $GITHUB_STEP_SUMMARY
          test -f docs_index_report.json && jq -r '
            "[件数] " + ( .issues|length|tostring ) + "\n" +
            ( .issues[0:10] | map("- " + .kind + ": " + .note) | join("\n") )
          ' docs_index_report.json >> $GITHUB_STEP_SUMMARY || echo "No report"
      - uses: actions/upload-artifact@v4
        if: ${{ always() && !(github.event_name == 'pull_request' && startsWith(github.head_ref, 'docs-sync/')) && !(github.event_name != 'pull_request' && startsWith(github.ref_name, 'docs-sync/')) && !(github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[skip docsync]')) }}
        with:
          name: ds14-report
          path: docs_index_report.json

  report-failure:
    needs: [validate]
    if: ${{ always() && github.event_name == 'pull_request' && !(startsWith(github.head_ref, 'docs-sync/')) && !(contains(github.event.pull_request.title, '[skip docsync]')) && failure() }}
    runs-on: ubuntu-latest
    permissions: { contents: read, pull-requests: write, issues: write }
    steps:
      - uses: actions/checkout@v4
      - name: Report docs index failure
        uses: ./.github/actions/on-failure
        with:
          pr-number: ${{ github.event.pull_request.number }}
          labels: docs:invalid
          message: |
            ❌ docs-index-validate failed.
            Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  report-success:
    needs: [validate]
    if: ${{ always() && github.event_name == 'pull_request' && !(startsWith(github.head_ref, 'docs-sync/')) && !(contains(github.event.pull_request.title, '[skip docsync]')) && needs.validate.result == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            core.info('triage:urgent removal is handled centrally by pr-label-guard. No action needed here.');
