name: docs-index-validate

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/docs-index-validate.yml'

permissions:
  contents: read

concurrency:
  group: docs-index-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    env:
      DOCSYNC_HEAD: ${{ (github.event_name == 'pull_request' && startsWith(github.head_ref, 'docs-sync/')) ||
        (github.event_name != 'pull_request' && startsWith(github.ref_name, 'docs-sync/')) }}
      DOCSYNC_SKIP_TITLE: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[skip docsync]') }}
    steps:
      - name: No-op on docs-sync PR
        if: ${{ env.DOCSYNC_HEAD == 'true' || env.DOCSYNC_SKIP_TITLE == 'true' }}
        run: echo "docs-sync PR: no-op (success)"
      - uses: actions/checkout@v4
        if: ${{ env.DOCSYNC_HEAD != 'true' && env.DOCSYNC_SKIP_TITLE != 'true' }}
      - uses: actions/setup-python@v5
        if: ${{ env.DOCSYNC_HEAD != 'true' && env.DOCSYNC_SKIP_TITLE != 'true' }}
        with:
          python-version: '3.11'
      - name: Validate docs index & links
        if: ${{ env.DOCSYNC_HEAD != 'true' && env.DOCSYNC_SKIP_TITLE != 'true' }}
        run: |
          python scripts/docs_index_validate.py || EXIT=$?
          echo "exit_code=${EXIT:-0}" >> $GITHUB_OUTPUT
          exit ${EXIT:-0}
      - name: Write summary
        if: ${{ always() && env.DOCSYNC_HEAD != 'true' && env.DOCSYNC_SKIP_TITLE != 'true' }}
        run: |
          echo "## DS-14 Report" >> $GITHUB_STEP_SUMMARY
          test -f docs_index_report.json && jq -r '
            "[件数] " + ( .issues|length|tostring ) + "\n" +
            ( .issues[0:10] | map("- " + .kind + ": " + .note) | join("\n") )
          ' docs_index_report.json >> $GITHUB_STEP_SUMMARY || echo "No report"
      - uses: actions/upload-artifact@v4
        if: ${{ always() && env.DOCSYNC_HEAD != 'true' && env.DOCSYNC_SKIP_TITLE != 'true' }}
        with:
          name: ds14-report
          path: docs_index_report.json
