name: ensure-labels
on:
  workflow_dispatch: {}
permissions:
  issues: write
jobs:
  ensure:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure required labels exist (idempotent)
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const wanted = [
              { name: 'docs:invalid',        color: 'd73a4a', description: 'Docs checks failed' },
              { name: 'docsync:needs-apply',  color: 'fbca04', description: 'DocSync apply needed' },
              { name: 'codex:apply',          color: '0e8a16', description: 'Codex applied' },
            ];
            for (const l of wanted) {
              try {
                // 既存なら更新、無ければ作成（idempotent）
                await github.rest.issues.getLabel({ owner, repo, name: l.name });
                await github.rest.issues.updateLabel({
                  owner, repo, name: l.name, color: l.color, description: l.description
                });
                core.info(`Updated label: ${l.name}`);
              } catch (e) {
                await github.rest.issues.createLabel({
                  owner, repo, name: l.name, color: l.color, description: l.description
                });
                core.info(`Created label: ${l.name}`);
              }
            }