name: nfr-xref
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      strict:
        description: 'Fail CI when deficits exceed threshold'
        required: false
        default: 'false'
      fail_streak:
        description: 'Threshold for consecutive deficits to fail'
        required: false
        default: '2'
permissions:
  contents: read

concurrency:
  group: nfr-xref-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: false

jobs:
  xref:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      DOCSYNC_SKIP: ${{ ((github.event_name == 'pull_request') && (startsWith(github.head_ref || '', 'docs-sync/') || contains(github.event.pull_request.title || '', '[skip docsync]'))) || (github.event_name != 'pull_request' && startsWith(github.ref_name || '', 'docs-sync/')) }}
      GH_APP_TOKEN_READY: ${{ (secrets.GH_APP_ID != '' && secrets.GH_INSTALLATION_ID != '' && secrets.GH_APP_PRIVATE_KEY != '') && 'true' || 'false' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize diff gate for pull_request
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "TARGET_HAS_CHANGES=false" >> $GITHUB_ENV

      - name: Initialize diff gate for main/dispatch
        if: ${{ github.event_name != 'pull_request' }}
        run: echo "TARGET_HAS_CHANGES=true" >> $GITHUB_ENV

      - name: Detect docs-related changes
        if: ${{ github.event_name == 'pull_request' && env.DOCSYNC_SKIP != 'true' }}
        id: detect
        run: |
          python scripts/detect_changed_files.py \
            --base "${{ github.event.pull_request.base.sha }}" \
            --patterns docs/** \
                       .github/workflows/nfr-xref.yml \
                       scripts/nfr_xref_check.py \
            --github-output "$GITHUB_OUTPUT" \
            --summary-title "nfr-xref diff gate"

      - name: Export diff result
        if: ${{ github.event_name == 'pull_request' && env.DOCSYNC_SKIP != 'true' }}
        run: echo "TARGET_HAS_CHANGES=${{ steps.detect.outputs.changed || 'false' }}" >> $GITHUB_ENV

      - name: DocSync automation guard
        if: ${{ env.DOCSYNC_SKIP == 'true' }}
        run: |
          echo "## nfr-xref" >> $GITHUB_STEP_SUMMARY
          echo "- docs-sync branch or [skip docsync] title detected; skipping" >> $GITHUB_STEP_SUMMARY

      - name: Diff gate summary
        if: ${{ env.DOCSYNC_SKIP != 'true' && env.TARGET_HAS_CHANGES != 'true' }}
        run: |
          echo "## nfr-xref" >> $GITHUB_STEP_SUMMARY
          echo "- diff gate: no matching docs files for pull_request" >> $GITHUB_STEP_SUMMARY

      - name: Setup Python
        if: ${{ env.DOCSYNC_SKIP != 'true' && env.TARGET_HAS_CHANGES == 'true' }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        if: ${{ env.DOCSYNC_SKIP != 'true' && env.TARGET_HAS_CHANGES == 'true' }}
        run: python -m pip install --upgrade pip PyYAML

      - name: Run NFR cross-reference
        if: ${{ env.DOCSYNC_SKIP != 'true' && env.TARGET_HAS_CHANGES == 'true' }}
        env:
          NFR_XREF_FAIL_STREAK: ${{ inputs.fail_streak || '2' }}
          NFR_XREF_STRICT: ${{ (github.event_name == 'workflow_dispatch' && inputs.strict) || 'false' }}
        run: python scripts/nfr_xref_check.py

      - name: Prepare docs-sync content
        if: ${{ env.DOCSYNC_SKIP != 'true' && env.TARGET_HAS_CHANGES == 'true' && github.event_name != 'pull_request' }}
        run: |
          if [ -f docs/agile/.nfr-xref-row ]; then
            row=$(cat docs/agile/.nfr-xref-row)
            printf "\n%s\n" "$row" >> docs/agile/report.md
            rm docs/agile/.nfr-xref-row
          else
            echo "no .nfr-xref-row (skip append)"
          fi

      - name: Create GitHub App token
        if: ${{ env.DOCSYNC_SKIP != 'true' && env.TARGET_HAS_CHANGES == 'true' && github.event_name != 'pull_request' && env.GH_APP_TOKEN_READY == 'true' }}
        id: app-token
        continue-on-error: true
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          installation-id: ${{ secrets.GH_INSTALLATION_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Create docs-sync PR ([skip docsync])
        if: ${{ env.DOCSYNC_SKIP != 'true' && env.TARGET_HAS_CHANGES == 'true' && github.event_name != 'pull_request' }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
          branch: docs-sync/nfr-xref
          base: main
          title: "[skip docsync] chore(docs): append DS-15 nfr-xref result"
          commit-message: "docs(report): append DS-15 nfr-xref row + update state"
          add-paths: |
            docs/agile/report.md
            docs/agile/nfr-xref-state.json
          labels: "docsync:needs-apply"
          delete-branch: true

  report-failure:
    needs: [xref]
    if: ${{ always() && github.event_name == 'pull_request' && !(startsWith(github.head_ref, 'docs-sync/')) && !(contains(github.event.pull_request.title, '[skip docsync]')) && failure() }}
    runs-on: ubuntu-latest
    permissions: { contents: read, pull-requests: write, issues: write }
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Report NFR xref failure
        uses: ./.github/actions/on-failure
        with:
          pr-number: ${{ github.event.pull_request.number }}
          labels: docs:invalid
          message: |
            ❌ nfr-xref failed.
            Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  report-success:
    needs: [xref]
    if: ${{ always() && github.event_name == 'pull_request' && !(startsWith(github.head_ref, 'docs-sync/')) && !(contains(github.event.pull_request.title, '[skip docsync]')) && needs.xref.result == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            // docs:invalid の除去は pr-label-guard に委譲（競合回避）
            const { owner, repo } = context.repo;
            const pr = context.payload.pull_request.number;
            try {
              await github.rest.issues.removeLabel({ owner, repo, issue_number: pr, name: 'triage:urgent' });
            } catch (error) {
              core.info(`triage:urgent removal skipped: ${error?.status === 404 ? 'label absent' : error?.message || error}`);
            }
