name: Node Playwright PoC

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to capture via Playwright'
        required: true
        type: string

jobs:
  capture:
    runs-on: ubuntu-22.04 # pin: 24.04 (ubuntu-latest) breaks Playwright deps
    permissions:
      contents: read
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: tools/ui-poc/package-lock.json

      - name: Install Node dependencies
        run: npm ci
        working-directory: tools/ui-poc

      - name: "Sanity: playwright resolves"
        working-directory: tools/ui-poc
        run: node -e "require.resolve('playwright'); console.log('playwright ok')"

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: tools/ui-poc

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Env snapshot (node/python/playwright)
        working-directory: tools/ui-poc
        run: |
          node -v
          npm -v
          python3 --version
          node -e "console.log('playwright', require('playwright/package.json').version)"

      - name: "Sanity: chromium headless launch"
        working-directory: tools/ui-poc
        run: node -e "require('playwright').chromium.launch({headless:true}).then(b=>b.close())"

      - name: Run capture (Python bridge)
        env:
          URL_INPUT: ${{ inputs.url }}
        shell: bash
        run: |
          python3 scripts/node_bridge.py --url "$URL_INPUT"

      - name: List artifacts (debug)
        if: always()
        run: ls -la artifacts/ui-poc || true

      - name: Upload capture artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-poc-artifacts
          path: artifacts/ui-poc
          if-no-files-found: ignore
