name: pr-label-guard
on:
  workflow_run:
    workflows: ["docs-index-validate", "nfr-xref", "security-permissions-lint"]
    types: [completed]
permissions:
  pull-requests: write
  issues: write
jobs:
  label:
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            // workflow_run payloadにはPRが無いケースもある（再実行等）
            const run = context.payload.workflow_run;
            const pr  = run.pull_requests?.[0];
            if (!pr) return;

            const { owner, repo } = context.repo;
            const number = pr.number;
            const failed = run.conclusion !== 'success';

            if (failed) {
              await github.rest.issues.addLabels({
                owner, repo, issue_number: number, labels: ['docs:invalid']
              });
            } else {
              try {
                await github.rest.issues.removeLabel({
                  owner, repo, issue_number: number, name: 'docs:invalid'
                });
              } catch (_) { /* labelが無ければ何もしない */ }
            }
