name: security-permissions-lint
on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read  # top-levelは最小権限を明示

concurrency:
  group: sec-review-docsync  # 固定キーで直列化
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: No-op on docs-sync or skip-title PR
        if: ${{ (github.event_name == 'pull_request' && startsWith(github.head_ref, 'docs-sync/')) || (github.event_name != 'pull_request' && startsWith(github.ref_name, 'docs-sync/')) || (github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[skip docsync]')) }}
        run: echo "docs-sync/skip-title PR: no-op (success)"

      - name: Skip for fork PR
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork }}
        run: echo "fork PR: lint skipped (success)"

      - name: Checkout
        if: ${{ !(github.event_name == 'pull_request' && startsWith(github.head_ref, 'docs-sync/')) && !(github.event_name != 'pull_request' && startsWith(github.ref_name, 'docs-sync/')) && !(github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[skip docsync]')) && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false) }}
        uses: actions/checkout@v4

      - name: Setup Python
        if: ${{ !(github.event_name == 'pull_request' && startsWith(github.head_ref, 'docs-sync/')) && !(github.event_name != 'pull_request' && startsWith(github.ref_name, 'docs-sync/')) && !(github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[skip docsync]')) && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false) }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        if: ${{ !(github.event_name == 'pull_request' && startsWith(github.head_ref, 'docs-sync/')) && !(github.event_name != 'pull_request' && startsWith(github.ref_name, 'docs-sync/')) && !(github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[skip docsync]')) && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false) }}
        run: python -m pip install --upgrade pip PyYAML

      - name: Run workflow permissions lint
        if: ${{ !(github.event_name == 'pull_request' && startsWith(github.head_ref, 'docs-sync/')) && !(github.event_name != 'pull_request' && startsWith(github.ref_name, 'docs-sync/')) && !(github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[skip docsync]')) && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false) }}
        env:
          SEC_LINT_STRICT: "false"  # Warn運用
        run: python scripts/workflow_permissions_lint.py

      - name: Append security review report
        if: ${{ always() && !(github.event_name == 'pull_request' && startsWith(github.head_ref, 'docs-sync/')) && !(github.event_name != 'pull_request' && startsWith(github.ref_name, 'docs-sync/')) && !(github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[skip docsync]')) && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false) }}
        run: |
          row=$(cat docs/agile/.sec-review-row)
          echo "$row | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> docs/agile/report.md

      - name: Create docs-sync pull request
        # fork PRやdocs-sync PRでは書込みをしない
        if: ${{ always() && !(github.event_name == 'pull_request' && startsWith(github.head_ref, 'docs-sync/')) && !(github.event_name != 'pull_request' && startsWith(github.ref_name, 'docs-sync/')) && !(github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[skip docsync]')) && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false) }}
        uses: peter-evans/create-pull-request@v6
        with:
          branch: docs-sync/sec-review
          base: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || 'main' }}
          title: "[skip docsync] chore(docs): append DS-21 sec-review result"
          commit-message: "docs(report): append DS-21 sec-review row"
          add-paths: docs/agile/report.md
          labels: "docsync:needs-apply"
          delete-branch: true
