name: security-permissions-lint
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main  # release/** を保護したくなったらここに追加
    paths:
      - .github/workflows/**
      - scripts/**

permissions:
  contents: read  # top-levelは最小権限を明示

concurrency:
  group: security-permissions-lint-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      pull-requests: write
    env:
      DOCSYNC_SKIP: ${{
        (github.event_name == 'pull_request' &&
          (startsWith(github.head_ref || '', 'docs-sync/') || contains(github.event.pull_request.title || '', '[skip docsync]')))
        || (github.event_name != 'pull_request' && startsWith(github.ref_name || '', 'docs-sync/'))
      }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize diff gate for pull_request
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "TARGET_HAS_CHANGES=false" >> $GITHUB_ENV

      - name: Initialize diff gate for push/dispatch
        if: ${{ github.event_name != 'pull_request' }}
        run: echo "TARGET_HAS_CHANGES=true" >> $GITHUB_ENV

      - name: Detect permission-related changes
        if: ${{ github.event_name == 'pull_request' && env.DOCSYNC_SKIP != 'true' }}
        id: detect
        run: |
          python scripts/detect_changed_files.py \
            --base "${{ github.event.pull_request.base.sha }}" \
            --patterns .github/workflows/** \
                       scripts/** \
                       .github/** \
            --github-output "$GITHUB_OUTPUT" \
            --summary-title "security-permissions diff gate"

      - name: Export diff result
        if: ${{ github.event_name == 'pull_request' && env.DOCSYNC_SKIP != 'true' }}
        run: echo "TARGET_HAS_CHANGES=${{ steps.detect.outputs.changed || 'false' }}" >> $GITHUB_ENV

      - name: DocSync automation guard
        if: ${{ env.DOCSYNC_SKIP == 'true' }}
        run: |
          echo "## security-permissions-lint" >> $GITHUB_STEP_SUMMARY
          echo "- docs-sync branch or [skip docsync] title detected; skipping" >> $GITHUB_STEP_SUMMARY

      - name: Diff gate summary
        if: ${{ env.DOCSYNC_SKIP != 'true' && env.TARGET_HAS_CHANGES != 'true' }}
        run: |
          echo "## security-permissions-lint" >> $GITHUB_STEP_SUMMARY
          echo "- diff gate: no relevant workflow/script changes" >> $GITHUB_STEP_SUMMARY

      - name: Setup Python
        if: ${{ env.DOCSYNC_SKIP != 'true' && env.TARGET_HAS_CHANGES == 'true' }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        if: ${{ env.DOCSYNC_SKIP != 'true' && env.TARGET_HAS_CHANGES == 'true' }}
        run: python -m pip install --upgrade pip PyYAML

      - name: Run workflow permissions lint
        if: ${{ env.DOCSYNC_SKIP != 'true' && env.TARGET_HAS_CHANGES == 'true' }}
        env:
          SEC_LINT_STRICT: "false"  # Warn運用
        run: python scripts/workflow_permissions_lint.py

      - name: Append security review report
        if: ${{ env.DOCSYNC_SKIP != 'true' && env.TARGET_HAS_CHANGES == 'true' && github.event_name != 'pull_request' && github.ref_name == 'main' }}
        run: |
          test -f docs/agile/.sec-review-row || echo "$(date +%F) | security-permissions-lint | auto | generated-by-workflow" > docs/agile/.sec-review-row
          row=$(cat docs/agile/.sec-review-row)
          echo "$row | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> docs/agile/report.md

      - name: Create GitHub App token
        if: ${{ env.DOCSYNC_SKIP != 'true' && env.TARGET_HAS_CHANGES == 'true' && github.event_name != 'pull_request' && github.ref_name == 'main' && secrets.GH_APP_ID != '' && secrets.GH_INSTALLATION_ID != '' && secrets.GH_APP_PRIVATE_KEY != '' }}
        id: app-token
        continue-on-error: true
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          installation-id: ${{ secrets.GH_INSTALLATION_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Create docs-sync pull request
        if: ${{ env.DOCSYNC_SKIP != 'true' && env.TARGET_HAS_CHANGES == 'true' && github.event_name != 'pull_request' && github.ref_name == 'main' }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
          branch: docs-sync/sec-review
          base: ${{ github.ref_name }}
          title: "[skip docsync] chore(docs): append DS-21 sec-review result"
          commit-message: "docs(report): append DS-21 sec-review row"
          add-paths: docs/agile/report.md
          labels: "docsync:needs-apply"
          delete-branch: true

      - name: PR向けサマリ
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "## security-permissions-lint" >> $GITHUB_STEP_SUMMARY
          if [ "${{ env.DOCSYNC_SKIP }}" = "true" ]; then
            echo "- docs-sync automation detected" >> $GITHUB_STEP_SUMMARY
          elif [ "${{ env.TARGET_HAS_CHANGES }}" != "true" ]; then
            echo "- diff gate skipped: no relevant files" >> $GITHUB_STEP_SUMMARY
          else
            echo "- diff gate matched relevant files; lint executed" >> $GITHUB_STEP_SUMMARY

  report-failure:
    needs: [lint]
    if: ${{ needs.lint.result == 'failure' && ((github.event_name == 'push' && github.ref_name == 'main') || (github.event_name == 'workflow_dispatch' && github.ref_name == 'main')) }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Open triage issue on failure
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const refName = process.env.GITHUB_REF_NAME || context.ref?.split('/')?.pop() || 'unknown';
            const title = `security-permissions-lint failed on ${refName}`;
            const runUrl = `${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`;
            const body = `Run: ${runUrl}`;

            const openIssues = await github.paginate(
              github.rest.issues.listForRepo,
              {
                owner,
                repo,
                state: 'open',
                labels: 'triage:urgent',
                per_page: 100,
              },
              (response) => response.data
            );

            if (!openIssues.some((issue) => issue.title === title)) {
              await github.rest.issues.create({ owner, repo, title, body, labels: ['triage:urgent'] });
              core.info('Created triage:urgent issue');
            } else {
              core.info('triage:urgent issue already open; skipping create');
            }

  report-success:
    needs: [lint]
    if: ${{ needs.lint.result == 'success' && ((github.event_name == 'push' && github.ref_name == 'main') || (github.event_name == 'workflow_dispatch' && github.ref_name == 'main')) }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Close triage issue on recovery
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const refName = process.env.GITHUB_REF_NAME || context.ref?.split('/')?.pop() || 'unknown';
            const title = `security-permissions-lint failed on ${refName}`;

            const openIssues = await github.paginate(
              github.rest.issues.listForRepo,
              {
                owner,
                repo,
                state: 'open',
                labels: 'triage:urgent',
                per_page: 100,
              },
              (response) => response.data
            );

            for (const issue of openIssues.filter((entry) => entry.title === title)) {
              await github.rest.issues.update({ owner, repo, issue_number: issue.number, state: 'closed' });
              core.info(`Closed issue #${issue.number}`);
            }
