name: soft-guard-alert
on:
  pull_request:
    types: [closed]
permissions:
  contents: read
  issues: write
jobs:
  alert:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - id: check
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const number = context.payload.pull_request.number;

            const labels = await github.paginate(
              github.rest.issues.listLabelsOnIssue,
              {owner, repo, issue_number: number}
            );
            const hasInvalid = labels.some(l => l.name === 'docs:invalid');
            core.setOutput('hasInvalid', String(hasInvalid));

            if (hasInvalid) {
              await github.rest.issues.create({
                owner, repo,
                title: `Soft guard violation: PR #${number} merged with docs:invalid`,
                body: context.payload.pull_request.html_url
              });
            }
      - if: ${{ steps.check.outputs.hasInvalid == 'true' && env.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"⚠️ Soft guard violation: PR #${{ github.event.pull_request.number }} merged with docs:invalid — ${{ github.event.pull_request.html_url }}\"}" \
            "$SLACK_WEBHOOK_URL"
