name: status-compat-seed

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch ref to seed statuses for (default: main)'
        required: false

permissions:
  contents: read
  statuses: write

concurrency:
  group: status-compat-seed-${{ github.event.pull_request.head.sha || github.sha }}
  cancel-in-progress: true

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - name: Emit pending statuses for DS-26 required contexts
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            let sha = context.payload.pull_request?.head?.sha;
            let refName = context.payload.pull_request?.head?.ref
              || context.payload.inputs?.ref
              || context.ref;

            if (!sha && refName) {
              const normalized = refName.startsWith('refs/')
                ? refName.replace(/^refs\//, '')
                : `heads/${refName}`;
              try {
                const { data } = await github.rest.git.getRef({
                  owner,
                  repo,
                  ref: normalized,
                });
                sha = data.object?.sha || sha;
              } catch (error) {
                core.warning(`Failed to resolve ref ${refName}: ${error.message}`);
              }
            }

            if (!sha) {
              core.warning('No head SHA; skip seeding statuses');
              return;
            }

            const contexts = [
              'docs-index-validate (pull_request)',
              'nfr-xref (pull_request)',
              'security-permissions-lint (pull_request)',
            ];

            for (const ctx of contexts) {
              await github.rest.repos.createCommitStatus({
                owner,
                repo,
                sha,
                state: 'pending',
                context: ctx,
                description: 'seed (PR diff gate pending full run)',
              });
            }

            await core.summary
              .addHeading('status-compat-seed')
              .addList(contexts.map((ctx) => `seeded: ${ctx} = pending @ ${sha.substring(0, 7)}`))
              .addRaw('\nPR diff gate only checks changed paths; push/workflow_dispatch(main) perform full validations.\n')
              .write();
